#!/bin/bash
set -e

# Setup the folder structure based on the specifications
mkdir -p JATIN_SCRIPT_FACTORY/00_MASTER
mkdir -p JATIN_SCRIPT_FACTORY/01_SHARED/contracts
mkdir -p JATIN_SCRIPT_FACTORY/01_SHARED/policies
mkdir -p JATIN_SCRIPT_FACTORY/02_BOTS
mkdir -p JATIN_SCRIPT_FACTORY/03_TESTS
mkdir -p JATIN_SCRIPT_FACTORY/04_FIXTURES
mkdir -p JATIN_SCRIPT_FACTORY/05_RUNS
mkdir -p JATIN_SCRIPT_FACTORY/06_EVIDENCE
mkdir -p JATIN_SCRIPT_FACTORY/07_RELEASES
mkdir -p JATIN_SCRIPT_FACTORY/08_OPTIONAL_RUNTIME/adapters
mkdir -p JATIN_SCRIPT_FACTORY/reports
mkdir -p JATIN_SCRIPT_FACTORY/sources

cp README_START_HERE.md JATIN_SCRIPT_FACTORY/
touch JATIN_SCRIPT_FACTORY/00_MASTER/PROJECT_INSTRUCTIONS.md
touch JATIN_SCRIPT_FACTORY/00_MASTER/WORKER_MASTER_COMMAND.md
echo "{}" > JATIN_SCRIPT_FACTORY/00_MASTER/BOT_REGISTRY.json
echo "{}" > JATIN_SCRIPT_FACTORY/00_MASTER/ROUTING_GRAPH.json
echo "{}" > JATIN_SCRIPT_FACTORY/00_MASTER/BUILD_STATUS.json

touch JATIN_SCRIPT_FACTORY/01_SHARED/policies/source_rules.md
touch JATIN_SCRIPT_FACTORY/01_SHARED/policies/originality.md
touch JATIN_SCRIPT_FACTORY/01_SHARED/policies/qa.md

touch JATIN_SCRIPT_FACTORY/03_TESTS/test_contracts.py
touch JATIN_SCRIPT_FACTORY/03_TESTS/test_routing.py
touch JATIN_SCRIPT_FACTORY/03_TESTS/test_fixtures.py

touch JATIN_SCRIPT_FACTORY/08_OPTIONAL_RUNTIME/orchestrator.py
touch JATIN_SCRIPT_FACTORY/08_OPTIONAL_RUNTIME/requirements.txt
